# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c0daf12b6f9119b4ddff68868554a38deb6d0762cfc334f8771af53a5c339323e5ef8b27b49e7f55b6feba9b11463c8273688b75147bdeb05f6818ae558d79f

test:
  secret_key_base: fd73ab24881dce28c86938d521fd2f4c45aa6733c0d4db43760feafd13d8a4f3ce1630aa904bd2dbaff2bbb7aac6c18e905e620ba057e55a54efe622f45b7c03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
